-- Generated by scripts/dump-schema.sh — do not edit by hand.
-- Regenerate after every schema change and commit the result.
-- Captures public-schema tables, constraints, indexes, functions,
-- row-level security and triggers. Data is never included.
--
-- Dumped: 2026-09-06T05:15:34Z

-- ── Extensions ─────────────────────────────────────────────────────────
create extension if not exists pg_cron;
create extension if not exists pg_stat_statements;
create extension if not exists pgcrypto;
create extension if not exists supabase_vault;
create extension if not exists "uuid-ossp";
create extension if not exists vector;

-- ── Tables ─────────────────────────────────────────────────────────────
create table if not exists annotations (
  id uuid default gen_random_uuid() not null,
  note_slug text not null,
  user_id uuid not null,
  data jsonb not null,
  updated_at timestamp with time zone default now(),
  firebase_uid text
);

create table if not exists book_chunks (
  id bigint default nextval('book_chunks_id_seq'::regclass) not null,
  content text not null,
  embedding vector(1024),
  book_title text,
  created_at timestamp without time zone default now(),
  author text
);

create table if not exists canvas_annotations (
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  note_slug text not null,
  strokes jsonb default '[]'::jsonb not null,
  updated_at timestamp with time zone default now(),
  firebase_uid text
);

create table if not exists chat_usage (
  id bigint default nextval('chat_usage_id_seq'::regclass) not null,
  user_id uuid,
  phone text not null,
  date date not null,
  count integer default 1 not null,
  firebase_uid text
);

create table if not exists contact_submissions (
  id uuid default gen_random_uuid() not null,
  type text not null,
  name text,
  email text,
  message text,
  page text,
  created_at timestamp with time zone default now()
);

create table if not exists debates (
  id uuid default gen_random_uuid() not null,
  title text not null,
  period text not null,
  topics text[] default '{}'::text[],
  upsc_tip text,
  type text default 'debate'::text,
  created_at timestamp with time zone default now(),
  paper text default 'Paper I'::text,
  title_hi text,
  upsc_tip_hi text
);

create table if not exists device_sessions (
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  session_id text not null,
  device_info text,
  created_at timestamp with time zone default now(),
  user_name text,
  user_email text,
  firebase_uid text
);

create table if not exists eval_usage (
  id bigint default nextval('eval_usage_id_seq'::regclass) not null,
  user_id uuid,
  phone text not null,
  date date not null,
  count integer default 1 not null
);

create table if not exists map_evaluations (
  id uuid default gen_random_uuid() not null,
  firebase_uid text not null,
  razorpay_payment_id text,
  razorpay_order_id text,
  created_at timestamp with time zone default now()
);

create table if not exists note_overrides (
  slug text not null,
  content text not null,
  updated_at timestamp with time zone default now()
);

create table if not exists notifications (
  id uuid default gen_random_uuid() not null,
  title text not null,
  link text not null,
  type text default 'general'::text,
  created_at timestamp with time zone default now()
);

create table if not exists payment_events (
  payment_id text not null,
  order_id text not null,
  firebase_uid text not null,
  email text,
  kind text default 'subscription'::text not null,
  plan text not null,
  amount_paise integer not null,
  expires_at timestamp with time zone,
  applied_at timestamp with time zone default now() not null
);

create table if not exists positions (
  id uuid default gen_random_uuid() not null,
  debate_id uuid,
  historian_name text not null,
  stance text not null,
  key_work text,
  argument text not null,
  school text,
  created_at timestamp with time zone default now(),
  argument_hi text,
  stance_hi text,
  key_work_hi text
);

create table if not exists posts (
  id text not null,
  type text not null,
  title text not null,
  excerpt text,
  content text not null,
  tags text[],
  cover_image text,
  published boolean default false,
  published_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  slug text
);

create table if not exists pyq_answers (
  id uuid default gen_random_uuid() not null,
  pyq_id integer not null,
  user_id uuid,
  display_name text not null,
  storage_path text not null,
  answer_number integer not null,
  created_at timestamp with time zone default now(),
  firebase_uid text
);

create table if not exists pyq_comments (
  id uuid default gen_random_uuid() not null,
  pyq_id integer not null,
  fingerprint text not null,
  display_name text not null,
  body text not null,
  upvotes integer default 0,
  created_at timestamp with time zone default now()
);

create table if not exists rate_limits (
  key text not null,
  count integer default 0 not null,
  window_start timestamp with time zone default now() not null
);

create table if not exists site_config (
  key text not null,
  value text not null,
  updated_at timestamp without time zone default now()
);

create table if not exists subscription_slots (
  id integer default 1 not null,
  max_slots integer default 45
);

create table if not exists subscriptions (
  id bigint default nextval('subscriptions_id_seq'::regclass) not null,
  user_id uuid,
  status text default 'active'::text not null,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone default now(),
  email text,
  plan text default 'yearly'::text,
  razorpay_order_id text,
  razorpay_payment_id text,
  firebase_uid text
);

create table if not exists topper_copies (
  id uuid default gen_random_uuid() not null,
  question text not null,
  drive_file_id text not null,
  note text,
  created_at timestamp with time zone default now()
);

create table if not exists topper_copy_pyq_map (
  topper_copy_id uuid not null,
  pyq_id integer not null
);

create table if not exists topper_subscriptions (
  id uuid default gen_random_uuid() not null,
  firebase_uid text not null,
  email text,
  razorpay_payment_id text,
  razorpay_order_id text,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone default now()
);

create table if not exists usage_tracking (
  id uuid default gen_random_uuid() not null,
  fingerprint text not null,
  eval_count integer default 0,
  chat_count integer default 0,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  firebase_uid text,
  topper_clicks integer default 0,
  name text
);

create table if not exists user_profiles (
  user_id uuid not null,
  phone text not null,
  updated_at timestamp with time zone default now(),
  firebase_uid text
);

create table if not exists user_sessions (
  id uuid default gen_random_uuid() not null,
  user_id uuid,
  visited_at timestamp with time zone default now(),
  visitor_id text,
  visit_count integer default 1,
  last_page text,
  referrer text,
  session_start timestamp with time zone default now(),
  last_active timestamp with time zone default now(),
  session_duration_secs integer default 0,
  device text,
  os text,
  browser text,
  pages_visited text[] default '{}'::text[],
  entry_page text,
  exit_page text,
  is_bounce boolean default true,
  country text,
  city text,
  firebase_uid text,
  name text
);

create table if not exists writing_pads (
  id uuid default gen_random_uuid() not null,
  name text default 'Untitled Pad'::text not null,
  data jsonb default '{"strokes": [], "textBoxes": [], "canvasWidth": 6000, "canvasHeight": 8000}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  user_id uuid
);


-- ── Constraints ────────────────────────────────────────────────────────
-- Primary keys, uniques, foreign keys and checks. The unique columns
-- here are what upsert onConflict targets rely on.
alter table annotations add constraint annotations_pkey PRIMARY KEY (id);
alter table annotations add constraint annotations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table book_chunks add constraint book_chunks_pkey PRIMARY KEY (id);
alter table canvas_annotations add constraint canvas_annotations_note_slug_user_id_key UNIQUE (note_slug, user_id);
alter table canvas_annotations add constraint canvas_annotations_pkey PRIMARY KEY (id);
alter table chat_usage add constraint chat_usage_phone_date_key UNIQUE (phone, date);
alter table chat_usage add constraint chat_usage_pkey PRIMARY KEY (id);
alter table chat_usage add constraint chat_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table contact_submissions add constraint contact_submissions_pkey PRIMARY KEY (id);
alter table debates add constraint debates_pkey PRIMARY KEY (id);
alter table device_sessions add constraint device_sessions_session_id_key UNIQUE (session_id);
alter table device_sessions add constraint device_sessions_pkey PRIMARY KEY (id);
alter table device_sessions add constraint device_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table eval_usage add constraint eval_usage_phone_date_key UNIQUE (phone, date);
alter table eval_usage add constraint eval_usage_pkey PRIMARY KEY (id);
alter table eval_usage add constraint eval_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table map_evaluations add constraint map_evaluations_pkey PRIMARY KEY (id);
alter table note_overrides add constraint note_overrides_pkey PRIMARY KEY (slug);
alter table notifications add constraint notifications_pkey PRIMARY KEY (id);
alter table payment_events add constraint payment_events_pkey PRIMARY KEY (payment_id);
alter table positions add constraint positions_pkey PRIMARY KEY (id);
alter table positions add constraint positions_debate_id_fkey FOREIGN KEY (debate_id) REFERENCES debates(id) ON DELETE CASCADE;
alter table posts add constraint posts_pkey PRIMARY KEY (id);
alter table pyq_answers add constraint pyq_answers_pkey PRIMARY KEY (id);
alter table pyq_comments add constraint pyq_comments_pkey PRIMARY KEY (id);
alter table rate_limits add constraint rate_limits_pkey PRIMARY KEY (key);
alter table site_config add constraint site_config_pkey PRIMARY KEY (key);
alter table subscription_slots add constraint subscription_slots_pkey PRIMARY KEY (id);
alter table subscription_slots add constraint subscription_slots_id_check CHECK ((id = 1));
alter table subscriptions add constraint subscriptions_firebase_uid_key UNIQUE (firebase_uid);
alter table subscriptions add constraint subscriptions_user_id_key UNIQUE (user_id);
alter table subscriptions add constraint subscriptions_pkey PRIMARY KEY (id);
alter table subscriptions add constraint subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table topper_copies add constraint topper_copies_pkey PRIMARY KEY (id);
alter table topper_copy_pyq_map add constraint topper_copy_pyq_map_pkey PRIMARY KEY (topper_copy_id, pyq_id);
alter table topper_copy_pyq_map add constraint topper_copy_pyq_map_topper_copy_id_fkey FOREIGN KEY (topper_copy_id) REFERENCES topper_copies(id) ON DELETE CASCADE;
alter table topper_subscriptions add constraint topper_subscriptions_firebase_uid_key UNIQUE (firebase_uid);
alter table topper_subscriptions add constraint topper_subscriptions_pkey PRIMARY KEY (id);
alter table usage_tracking add constraint usage_tracking_fingerprint_key UNIQUE (fingerprint);
alter table usage_tracking add constraint usage_tracking_firebase_uid_key UNIQUE (firebase_uid);
alter table usage_tracking add constraint usage_tracking_pkey PRIMARY KEY (id);
alter table user_profiles add constraint user_profiles_phone_key UNIQUE (phone);
alter table user_profiles add constraint user_profiles_pkey PRIMARY KEY (user_id);
alter table user_profiles add constraint user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table user_sessions add constraint user_sessions_pkey PRIMARY KEY (id);
alter table user_sessions add constraint user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
alter table writing_pads add constraint writing_pads_pkey PRIMARY KEY (id);
alter table writing_pads add constraint writing_pads_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);

-- ── Indexes ────────────────────────────────────────────────────────────
CREATE UNIQUE INDEX annotations_firebase_note_idx ON public.annotations USING btree (firebase_uid, note_slug);
CREATE UNIQUE INDEX annotations_note_slug_user_id_idx ON public.annotations USING btree (note_slug, user_id);
CREATE INDEX book_chunks_embedding_idx ON public.book_chunks USING hnsw (embedding vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE UNIQUE INDEX canvas_annotations_firebase_note_idx ON public.canvas_annotations USING btree (firebase_uid, note_slug);
CREATE INDEX device_sessions_user_id_idx ON public.device_sessions USING btree (user_id);
CREATE INDEX idx_notifications_created_at ON public.notifications USING btree (created_at DESC);
CREATE INDEX payment_events_order_idx ON public.payment_events USING btree (order_id);
CREATE INDEX payment_events_uid_idx ON public.payment_events USING btree (firebase_uid, applied_at DESC);
CREATE UNIQUE INDEX posts_slug_idx ON public.posts USING btree (slug);
CREATE INDEX pyq_answers_pyq_id_idx ON public.pyq_answers USING btree (pyq_id);
CREATE INDEX pyq_answers_user_id_idx ON public.pyq_answers USING btree (user_id);
CREATE INDEX pyq_comments_pyq_id_idx ON public.pyq_comments USING btree (pyq_id);
CREATE INDEX rate_limits_window_start_idx ON public.rate_limits USING btree (window_start);
CREATE INDEX topper_copy_pyq_map_pyq_id_idx ON public.topper_copy_pyq_map USING btree (pyq_id);
CREATE UNIQUE INDEX usage_tracking_fingerprint_idx ON public.usage_tracking USING btree (fingerprint);
CREATE INDEX usage_tracking_firebase_uid_idx ON public.usage_tracking USING btree (firebase_uid);
CREATE UNIQUE INDEX user_profiles_firebase_uid_idx ON public.user_profiles USING btree (firebase_uid);
CREATE UNIQUE INDEX user_sessions_visitor_id_key ON public.user_sessions USING btree (visitor_id) WHERE (visitor_id IS NOT NULL);
CREATE INDEX writing_pads_updated_at_idx ON public.writing_pads USING btree (updated_at DESC);

-- ── Functions ──────────────────────────────────────────────────────────
-- Extension-owned functions are excluded. pgvector alone installs ~95 of
-- them into public (halfvec_*, vector_*), which would conflict on replay
-- and bury the handful this project actually defines.
CREATE OR REPLACE FUNCTION public.check_rate_limit(p_key text, p_limit integer, p_window_seconds integer)
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
declare
  v_count integer;
begin
  insert into rate_limits as r (key, count, window_start)
  values (p_key, 1, now())
  on conflict (key) do update
    set count = case
          when r.window_start < now() - make_interval(secs => p_window_seconds)
            then 1
          else r.count + 1
        end,
        window_start = case
          when r.window_start < now() - make_interval(secs => p_window_seconds)
            then now()
          else r.window_start
        end
  returning r.count into v_count;

  -- Keys for callers that never return would otherwise accumulate forever.
  -- Cleaning up on roughly 1 in 1000 calls keeps the table bounded without
  -- needing a scheduled job.
  if random() < 0.001 then
    delete from rate_limits where window_start < now() - interval '1 day';
  end if;

  return v_count <= p_limit;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.consume_usage(p_uid text, p_fp text, p_field text, p_limit integer)
 RETURNS TABLE(allowed boolean, used integer)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_used integer := 0; v_new integer; v_updated integer := 0; v_rows integer;
  k_uid bigint; k_fp bigint;
begin
  if p_field not in ('eval_count','chat_count','topper_clicks') then
    raise exception 'unsupported field %', p_field;
  end if;
  if coalesce(p_uid,'') = '' and coalesce(p_fp,'') = '' then
    return query select false, 0; return;
  end if;
  k_uid := hashtext('usage:uid:' || coalesce(p_uid,''));
  k_fp := hashtext('usage:fp:' || coalesce(p_fp,''));
  if coalesce(p_uid,'') <> '' and coalesce(p_fp,'') <> '' then
    perform pg_advisory_xact_lock(least(k_uid,k_fp));
    perform pg_advisory_xact_lock(greatest(k_uid,k_fp));
  elsif coalesce(p_uid,'') <> '' then
    perform pg_advisory_xact_lock(k_uid);
  else
    perform pg_advisory_xact_lock(k_fp);
  end if;
  execute format('select coalesce(max(%I),0) from usage_tracking where (nullif($1,'''') is not null and firebase_uid = $1) or (nullif($2,'''') is not null and fingerprint = $2)', p_field)
    into v_used using coalesce(p_uid,''), coalesce(p_fp,'');
  if v_used >= p_limit then
    return query select false, v_used; return;
  end if;
  v_new := v_used + 1;
  if coalesce(p_uid,'') <> '' then
    execute format('update usage_tracking set %I = $2, updated_at = now() where firebase_uid = $1', p_field) using p_uid, v_new;
    get diagnostics v_rows = row_count; v_updated := v_updated + v_rows;
  end if;
  if coalesce(p_fp,'') <> '' then
    execute format('update usage_tracking set %I = $2, updated_at = now() where fingerprint = $1', p_field) using p_fp, v_new;
    get diagnostics v_rows = row_count; v_updated := v_updated + v_rows;
  end if;
  if v_updated = 0 then
    execute format('insert into usage_tracking (fingerprint, firebase_uid, %I) values (coalesce(nullif($1,''''), ''uid_'' || $2), nullif($2,''''), $3) on conflict do nothing', p_field)
      using coalesce(p_fp,''), coalesce(p_uid,''), v_new;
  end if;
  return query select true, v_new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.delete_zero_duration_sessions()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.session_duration_secs = 0 THEN
    RETURN NULL;
  END IF;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.match_book_chunks(query_embedding vector, match_count integer DEFAULT 10, filter_book text DEFAULT NULL::text)
 RETURNS TABLE(id bigint, content text, book_title text, author text, similarity double precision)
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN QUERY
  SELECT
    bc.id,
    bc.content,
    bc.book_title,
    bc.author,
    1 - (bc.embedding <=> query_embedding) AS similarity
  FROM book_chunks bc
  WHERE
    (filter_book IS NULL OR bc.book_title = filter_book)
    AND bc.embedding IS NOT NULL
  ORDER BY bc.embedding <=> query_embedding
  LIMIT match_count;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.match_book_chunks(query_embedding vector, match_count integer DEFAULT 5)
 RETURNS TABLE(content text, book_title text, author text, similarity double precision)
 LANGUAGE sql
 STABLE
AS $function$
  select content, book_title, author, 1 - (embedding <=> query_embedding) as similarity
  from book_chunks
  order by embedding <=> query_embedding
  limit match_count;
$function$
;

CREATE OR REPLACE FUNCTION public.match_book_chunks_diverse(query_embedding vector, per_book_count integer DEFAULT 3)
 RETURNS TABLE(id bigint, content text, book_title text, author text, similarity double precision)
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN QUERY
  SELECT
    bc.id,
    bc.content,
    bc.book_title,
    bc.author,
    1 - (bc.embedding <=> query_embedding) AS similarity
  FROM book_chunks bc
  WHERE bc.embedding IS NOT NULL
  ORDER BY bc.embedding <=> query_embedding
  LIMIT 50;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.merge_visitor(p_old_id text, p_new_id text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if coalesce(p_old_id, '') = '' or coalesce(p_new_id, '') = '' or p_old_id = p_new_id then
    return;
  end if;
  if exists (select 1 from user_sessions where visitor_id = p_new_id) then
    return;
  end if;
  update user_sessions set visitor_id = p_new_id where visitor_id = p_old_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.record_visit(p_visitor_id text, p_page text, p_referrer text DEFAULT NULL::text, p_device text DEFAULT NULL::text, p_os text DEFAULT NULL::text, p_browser text DEFAULT NULL::text, p_country text DEFAULT NULL::text, p_city text DEFAULT NULL::text, p_firebase_uid text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  -- Distinct pages only, and capped. The page name arrives from the browser,
  -- so without a ceiling a caller could grow one row without limit by sending
  -- a fresh path each time.
  k_max_pages constant integer := 200;
begin
  if coalesce(p_visitor_id, '') = '' then
    return;
  end if;

  insert into user_sessions (
    visitor_id, visit_count, visited_at, last_active, session_start,
    last_page, entry_page, exit_page, pages_visited, referrer,
    device, os, browser, country, city, is_bounce, firebase_uid,
    session_duration_secs
  )
  values (
    p_visitor_id, 1, now(), now(), now(),
    p_page, p_page, p_page,
    case when coalesce(p_page, '') = '' then '{}'::text[] else array[p_page] end,
    coalesce(nullif(p_referrer, ''), 'direct'),
    coalesce(nullif(p_device, ''), 'unknown'),
    coalesce(nullif(p_os, ''), 'unknown'),
    coalesce(nullif(p_browser, ''), 'unknown'),
    nullif(p_country, ''), nullif(p_city, ''),
    true, nullif(p_firebase_uid, ''), 0
  )
  on conflict (visitor_id) where visitor_id is not null do update set
    visit_count = user_sessions.visit_count + 1,
    visited_at  = now(),
    last_active = now(),
    last_page   = coalesce(nullif(p_page, ''), user_sessions.last_page),
    exit_page   = coalesce(nullif(p_page, ''), user_sessions.exit_page),

    pages_visited = case
      when coalesce(p_page, '') = ''                          then user_sessions.pages_visited
      when p_page = any(user_sessions.pages_visited)          then user_sessions.pages_visited
      when cardinality(user_sessions.pages_visited) >= k_max_pages
                                                              then user_sessions.pages_visited
      else user_sessions.pages_visited || p_page
    end,

    -- A visitor who has seen more than one distinct page did not bounce.
    is_bounce = cardinality(case
      when coalesce(p_page, '') = ''                          then user_sessions.pages_visited
      when p_page = any(user_sessions.pages_visited)          then user_sessions.pages_visited
      when cardinality(user_sessions.pages_visited) >= k_max_pages
                                                              then user_sessions.pages_visited
      else user_sessions.pages_visited || p_page
    end) <= 1,

    session_duration_secs = greatest(
      0,
      extract(epoch from now() - coalesce(user_sessions.session_start, now()))::integer
    ),

    -- Later requests may know things the first did not, but must never
    -- overwrite a known value with 'unknown'.
    device       = coalesce(nullif(p_device, ''),  user_sessions.device),
    os           = coalesce(nullif(p_os, ''),      user_sessions.os),
    browser      = coalesce(nullif(p_browser, ''), user_sessions.browser),
    country      = coalesce(nullif(p_country, ''), user_sessions.country),
    city         = coalesce(nullif(p_city, ''),    user_sessions.city),
    firebase_uid = coalesce(nullif(p_firebase_uid, ''), user_sessions.firebase_uid);
end;
$function$
;

CREATE OR REPLACE FUNCTION public.release_usage(p_uid text, p_fp text, p_field text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if p_field not in ('eval_count','chat_count','topper_clicks') then
    raise exception 'unsupported field %', p_field;
  end if;
  execute format('update usage_tracking set %I = greatest(coalesce(%I,0) - 1, 0), updated_at = now() where (nullif($1,'''') is not null and firebase_uid = $1) or (nullif($2,'''') is not null and fingerprint = $2)', p_field, p_field)
    using coalesce(p_uid,''), coalesce(p_fp,'');
end;
$function$
;

CREATE OR REPLACE FUNCTION public.touch_visit(p_visitor_id text)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  update user_sessions
     set last_active = now(),
         session_duration_secs = greatest(
           0, extract(epoch from now() - coalesce(session_start, now()))::integer
         )
   where visitor_id = p_visitor_id;
$function$
;


-- ── Row-level security ─────────────────────────────────────────────────
alter table annotations enable row level security;
alter table book_chunks enable row level security;
alter table canvas_annotations enable row level security;
alter table chat_usage enable row level security;
alter table contact_submissions enable row level security;
alter table debates enable row level security;
alter table device_sessions enable row level security;
alter table eval_usage enable row level security;
alter table map_evaluations enable row level security;
alter table note_overrides enable row level security;
alter table notifications enable row level security;
alter table payment_events enable row level security;
alter table positions enable row level security;
alter table posts enable row level security;
alter table pyq_answers enable row level security;
alter table pyq_comments enable row level security;
alter table rate_limits enable row level security;
alter table site_config enable row level security;
alter table subscription_slots enable row level security;
alter table subscriptions enable row level security;
alter table topper_copies enable row level security;
alter table topper_copy_pyq_map enable row level security;
alter table topper_subscriptions enable row level security;
alter table usage_tracking enable row level security;
alter table user_profiles enable row level security;
alter table user_sessions enable row level security;
alter table writing_pads enable row level security;

-- Policies. A table with RLS on and no policy denies every non-service role.
create policy "own annotations" on annotations as PERMISSIVE for ALL to public using ((auth.uid() = user_id));
create policy "Users manage own canvas annotations" on canvas_annotations as PERMISSIVE for ALL to public using ((auth.uid() = user_id));
create policy "Users manage own chat usage" on chat_usage as PERMISSIVE for ALL to public using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Allow insert only" on contact_submissions as PERMISSIVE for INSERT to public with check (true);
create policy "Admin all debates" on debates as PERMISSIVE for ALL to public using (true) with check (true);
create policy "Public read debates" on debates as PERMISSIVE for SELECT to public using (true);
create policy "Service role full access" on device_sessions as PERMISSIVE for ALL to service_role using (true) with check (true);
create policy "Users manage own usage" on eval_usage as PERMISSIVE for ALL to public using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "read overrides" on note_overrides as PERMISSIVE for SELECT to public using (true);
create policy "Public can read notifications" on notifications as PERMISSIVE for SELECT to anon, authenticated using (true);
create policy "Admin all positions" on positions as PERMISSIVE for ALL to public using (true) with check (true);
create policy "Public read positions" on positions as PERMISSIVE for SELECT to public using (true);
create policy "read published posts" on posts as PERMISSIVE for SELECT to public using ((published = true));
create policy "Auth delete" on pyq_answers as PERMISSIVE for DELETE to public using ((auth.uid() = user_id));
create policy "Auth insert" on pyq_answers as PERMISSIVE for INSERT to public with check ((auth.uid() = user_id));
create policy "Public read" on pyq_answers as PERMISSIVE for SELECT to public using (true);
create policy "anyone can insert" on pyq_comments as PERMISSIVE for INSERT to public with check (true);
create policy "anyone can read" on pyq_comments as PERMISSIVE for SELECT to public using (true);
create policy "anyone can upvote" on pyq_comments as PERMISSIVE for UPDATE to public using (true);
create policy "Allow read only" on subscription_slots as PERMISSIVE for SELECT to public using (true);
create policy "Users read own subscription" on subscriptions as PERMISSIVE for SELECT to public using ((auth.uid() = user_id));
create policy "Public can read topper_copies" on topper_copies as PERMISSIVE for SELECT to public using (true);
create policy "Public can read topper_copy_pyq_map" on topper_copy_pyq_map as PERMISSIVE for SELECT to public using (true);
create policy "service role only" on topper_subscriptions as PERMISSIVE for ALL to public using (false);
create policy "Allow all for service role" on usage_tracking as PERMISSIVE for ALL to public using (true) with check (true);
create policy "Users manage own profile" on user_profiles as PERMISSIVE for ALL to public using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Allow all for service role" on user_sessions as PERMISSIVE for ALL to public using (true) with check (true);
create policy allow_visitor_tracking on user_sessions as PERMISSIVE for ALL to public using (true) with check (true);
create policy service_only on user_sessions as PERMISSIVE for ALL to public using (false) with check (false);
create policy "Users can delete own pads" on writing_pads as PERMISSIVE for DELETE to public using ((auth.uid() = user_id));
create policy "Users can insert own pads" on writing_pads as PERMISSIVE for INSERT to public with check ((auth.uid() = user_id));
create policy "Users can update own pads" on writing_pads as PERMISSIVE for UPDATE to public using ((auth.uid() = user_id));
create policy "Users can view own pads" on writing_pads as PERMISSIVE for SELECT to public using ((auth.uid() = user_id));

-- ── Triggers ───────────────────────────────────────────────────────────
