// AUTO-GENERATED: UPSC History Optional Map Questions 2013–2025
// Total entries: 260 (13 years × 20 questions)

export interface MapEntry {
  year: number;
  number: number;
  hint: string;
  answer: string;
  lat: number;
  lng: number;
}

export const mapData: MapEntry[] = [
  // ── 2013 ──────────────────────────────────────────────────────────────────
  { year: 2013, number: 1,  hint: "A Palaeolithic and Mesolithic site",             answer: "Barudih",                   lat: 22.8,  lng: 85.9  },
  { year: 2013, number: 2,  hint: "A Mesolithic site",                              answer: "Bagor",                     lat: 24.9,  lng: 74.6  },
  { year: 2013, number: 3,  hint: "An important halting place",                     answer: "Bamiyan",                   lat: 34.8,  lng: 67.8  },
  { year: 2013, number: 4,  hint: "A pre-Harappan site",                            answer: "Amri",                      lat: 26.1,  lng: 68.0  },
  { year: 2013, number: 5,  hint: "An important Harappan site",                     answer: "Desalpur",                  lat: 23.5,  lng: 69.1  },
  { year: 2013, number: 6,  hint: "Site of important fossils",                      answer: "Hathnora",                  lat: 23.1,  lng: 77.5  },
  { year: 2013, number: 7,  hint: "A Sea-port",                                     answer: "Korkai",                    lat: 8.5,   lng: 78.1  },
  { year: 2013, number: 8,  hint: "A Palaeolithic site",                            answer: "Hunsgi",                    lat: 16.8,  lng: 76.6  },
  { year: 2013, number: 9,  hint: "A Neolithic, Megalithic and Chalcolithic site",  answer: "Hallur",                    lat: 14.5,  lng: 75.9  },
  { year: 2013, number: 10, hint: "A Harappan site",                                answer: "Alamgirpur",                lat: 28.9,  lng: 77.7  },
  { year: 2013, number: 11, hint: "A Palaeolithic site",                            answer: "Didwana",                   lat: 27.4,  lng: 74.6  },
  { year: 2013, number: 12, hint: "A Neolithic site",                               answer: "Chirand",                   lat: 25.9,  lng: 84.7  },
  { year: 2013, number: 13, hint: "A Chalcolithic site",                            answer: "Jorwe",                     lat: 19.3,  lng: 74.5  },
  { year: 2013, number: 14, hint: "A Chalcolithic site",                            answer: "Pandu Rajar Dhibi",          lat: 23.3,  lng: 87.9  },
  { year: 2013, number: 15, hint: "A site of Buddhist Monastery",                   answer: "Alchi Monastery",           lat: 34.2,  lng: 77.2  },
  { year: 2013, number: 16, hint: "Painted Grey Ware site",                         answer: "Ahichchhatra",              lat: 28.4,  lng: 79.1  },
  { year: 2013, number: 17, hint: "Site related to a famous Indian Philosopher",    answer: "Kaladi",                    lat: 10.2,  lng: 76.4  },
  { year: 2013, number: 18, hint: "Historical Rock-cut caves",                      answer: "Udayagiri Khandagiri",      lat: 20.3,  lng: 85.8  },
  { year: 2013, number: 19, hint: "Famous Fort",                                    answer: "Fort St. George",           lat: 13.1,  lng: 80.3  },
  { year: 2013, number: 20, hint: "Capital of famous Kingdom",                      answer: "Nagarjunakonda",            lat: 16.5,  lng: 79.3  },

  // ── 2014 ──────────────────────────────────────────────────────────────────
  { year: 2014, number: 1,  hint: "An ancient capital",                             answer: "Uraiyur",                   lat: 10.8,  lng: 78.7  },
  { year: 2014, number: 2,  hint: "A Palaeolithic site",                            answer: "Bhimbetka",                 lat: 22.9,  lng: 77.6  },
  { year: 2014, number: 3,  hint: "A cultural centre",                              answer: "Nalanda",                   lat: 25.1,  lng: 85.4  },
  { year: 2014, number: 4,  hint: "An ancient capital",                             answer: "Purushpura",                lat: 34.0,  lng: 71.6  },
  { year: 2014, number: 5,  hint: "A Palaeolithic site",                            answer: "Renigunta",                 lat: 13.6,  lng: 79.5  },
  { year: 2014, number: 6,  hint: "A historical site",                              answer: "Manyakheta",                lat: 17.5,  lng: 76.6  },
  { year: 2014, number: 7,  hint: "A Harappan site",                                answer: "Ropar",                     lat: 30.9,  lng: 76.5  },
  { year: 2014, number: 8,  hint: "An ancient capital",                             answer: "Pragjyotishpura",           lat: 26.2,  lng: 91.7  },
  { year: 2014, number: 9,  hint: "A political and cultural centre",                answer: "Pratishthana",              lat: 19.5,  lng: 75.4  },
  { year: 2014, number: 10, hint: "Megalithic site",                                answer: "Brahmagiri",                lat: 14.9,  lng: 76.8  },
  { year: 2014, number: 11, hint: "A Mesolithic site",                              answer: "Sarai Nahar Rai",           lat: 25.4,  lng: 81.9  },
  { year: 2014, number: 12, hint: "A Chalcolithic site",                            answer: "Lal Qila",                  lat: 28.7,  lng: 77.2  },
  { year: 2014, number: 13, hint: "A prehistoric site",                             answer: "Adamgarh",                  lat: 22.7,  lng: 77.7  },
  { year: 2014, number: 14, hint: "A political and cultural centre",                answer: "Takshashila",               lat: 33.7,  lng: 72.8  },
  { year: 2014, number: 15, hint: "An ancient capital",                             answer: "Srinagar",                  lat: 34.1,  lng: 74.8  },
  { year: 2014, number: 16, hint: "A lost port",                                    answer: "Puhar/Kaveripattanam",      lat: 11.1,  lng: 79.8  },
  { year: 2014, number: 17, hint: "Rock-cave art centre",                           answer: "Nashik/Pandavleni caves",   lat: 19.9,  lng: 73.7  },
  { year: 2014, number: 18, hint: "An ancient capital",                             answer: "Kapilavastu",               lat: 27.6,  lng: 83.1  },
  { year: 2014, number: 19, hint: "A political and cultural centre",                answer: "Vallabhi",                  lat: 21.9,  lng: 71.9  },
  { year: 2014, number: 20, hint: "An ancient town",                                answer: "Mathura",                   lat: 27.5,  lng: 77.7  },

  // ── 2015 ──────────────────────────────────────────────────────────────────
  { year: 2015, number: 1,  hint: "A Neolithic site",                               answer: "Burzahom",                  lat: 34.2,  lng: 74.9  },
  { year: 2015, number: 2,  hint: "A Neolithic site",                               answer: "Mehrgarh",                  lat: 29.4,  lng: 67.6  },
  { year: 2015, number: 3,  hint: "A Harappan site",                                answer: "Kalibangan",                lat: 29.5,  lng: 74.1  },
  { year: 2015, number: 4,  hint: "A Megalithic site",                              answer: "Adichanallur",              lat: 8.7,   lng: 77.8  },
  { year: 2015, number: 5,  hint: "A Harappan site",                                answer: "Surkotada",                 lat: 23.6,  lng: 70.8  },
  { year: 2015, number: 6,  hint: "A Painted-Grey-ware site",                       answer: "Hastinapur",                lat: 29.2,  lng: 78.0  },
  { year: 2015, number: 7,  hint: "An inscriptional site",                          answer: "Junagarh",                  lat: 21.5,  lng: 70.5  },
  { year: 2015, number: 8,  hint: "An important ancient city",                      answer: "Vidisha",                   lat: 23.5,  lng: 77.8  },
  { year: 2015, number: 9,  hint: "An ancient port",                                answer: "Tamralipti",                lat: 22.4,  lng: 87.9  },
  { year: 2015, number: 10, hint: "A site of ancient cave-painting",                answer: "Sittanavasal",              lat: 10.5,  lng: 78.9  },
  { year: 2015, number: 11, hint: "A Buddhist site",                                answer: "Amaravati",                 lat: 16.6,  lng: 80.4  },
  { year: 2015, number: 12, hint: "An educational centre",                          answer: "Vikramashila",              lat: 25.3,  lng: 87.3  },
  { year: 2015, number: 13, hint: "Brahmadeya village",                             answer: "Uttaramerur",               lat: 12.6,  lng: 79.8  },
  { year: 2015, number: 14, hint: "An ancient capital",                             answer: "Badami",                    lat: 15.9,  lng: 75.7  },
  { year: 2015, number: 15, hint: "An ancient capital",                             answer: "Kampilya",                  lat: 27.6,  lng: 79.3  },
  { year: 2015, number: 16, hint: "A temple site",                                  answer: "Bhubaneshwar",              lat: 20.3,  lng: 85.8  },
  { year: 2015, number: 17, hint: "An ancient capital",                             answer: "Halebidu/Dwarasamudra",     lat: 13.2,  lng: 75.9  },
  { year: 2015, number: 18, hint: "An ancient sea-port",                            answer: "Muchiris/Muziris",          lat: 10.2,  lng: 76.2  },
  { year: 2015, number: 19, hint: "An archaeological temple site",                  answer: "Dah Parbatiya",             lat: 26.5,  lng: 92.7  },
  { year: 2015, number: 20, hint: "A Harappan site",                                answer: "Rakhigarhi",                lat: 29.3,  lng: 76.1  },

  // ── 2016 ──────────────────────────────────────────────────────────────────
  { year: 2016, number: 1,  hint: "A Mesolithic site",                              answer: "Sarai Nahar Rai",           lat: 25.4,  lng: 81.9  },
  { year: 2016, number: 2,  hint: "A Neolithic site",                               answer: "Daojali Hading",            lat: 25.1,  lng: 93.4  },
  { year: 2016, number: 3,  hint: "A Megalithic-Chalcolithic site",                 answer: "Adichanallur",              lat: 8.7,   lng: 77.8  },
  { year: 2016, number: 4,  hint: "A Neolithic site",                               answer: "Kuchai",                    lat: 21.9,  lng: 86.1  },
  { year: 2016, number: 5,  hint: "A Neolithic site",                               answer: "Maski",                     lat: 15.9,  lng: 76.7  },
  { year: 2016, number: 6,  hint: "A Megalithic site",                              answer: "Junapani",                  lat: 21.3,  lng: 79.1  },
  { year: 2016, number: 7,  hint: "A site known for Buddhist remains",              answer: "Sanghol",                   lat: 30.7,  lng: 76.4  },
  { year: 2016, number: 8,  hint: "A Harappan site",                                answer: "Banawali",                  lat: 29.6,  lng: 75.4  },
  { year: 2016, number: 9,  hint: "A Harappan site",                                answer: "Kalibangan",                lat: 29.5,  lng: 74.1  },
  { year: 2016, number: 10, hint: "A Harappan site",                                answer: "Harappa",                   lat: 30.6,  lng: 72.9  },
  { year: 2016, number: 11, hint: "A Neolithic site",                               answer: "Mehrgarh",                  lat: 29.4,  lng: 67.6  },
  { year: 2016, number: 12, hint: "A Harappan site",                                answer: "Rojdi",                     lat: 22.0,  lng: 70.8  },
  { year: 2016, number: 13, hint: "A capital city",                                 answer: "Chittor",                   lat: 24.9,  lng: 74.6  },
  { year: 2016, number: 14, hint: "A rock-cut cave site",                           answer: "Bagh caves",                lat: 22.3,  lng: 74.8  },
  { year: 2016, number: 15, hint: "A Late Harappan site",                           answer: "Manda",                     lat: 32.5,  lng: 75.1  },
  { year: 2016, number: 16, hint: "An educational centre",                          answer: "Vikramashila",              lat: 25.3,  lng: 87.3  },
  { year: 2016, number: 17, hint: "A terracotta art centre",                        answer: "Chandraketugarh",           lat: 22.7,  lng: 88.6  },
  { year: 2016, number: 18, hint: "A seaport",                                      answer: "Muziris/Muchiris",          lat: 10.2,  lng: 76.2  },
  { year: 2016, number: 19, hint: "A capital city",                                 answer: "Vengi",                     lat: 16.8,  lng: 81.1  },
  { year: 2016, number: 20, hint: "A capital city",                                 answer: "Mandi",                     lat: 31.7,  lng: 76.9  },

  // ── 2017 ──────────────────────────────────────────────────────────────────
  { year: 2017, number: 1,  hint: "A Prehistoric cave-paintings site",              answer: "Bhimbetka",                 lat: 22.9,  lng: 77.6  },
  { year: 2017, number: 2,  hint: "A Neolithic-Chalcolithic site",                  answer: "Hallur",                    lat: 14.5,  lng: 75.9  },
  { year: 2017, number: 3,  hint: "An Early Harappan site",                         answer: "Banawali",                  lat: 29.6,  lng: 75.4  },
  { year: 2017, number: 4,  hint: "A Harappan site",                                answer: "Amri/Chanhudaro",           lat: 26.1,  lng: 68.0  },
  { year: 2017, number: 5,  hint: "An ancient capital city",                        answer: "Sirpur",                    lat: 21.6,  lng: 82.8  },
  { year: 2017, number: 6,  hint: "A Painted Grey Ware site",                       answer: "Ahichchhatra",              lat: 28.4,  lng: 79.1  },
  { year: 2017, number: 7,  hint: "A Neolithic site",                               answer: "Burzahom",                  lat: 34.2,  lng: 74.9  },
  { year: 2017, number: 8,  hint: "A site of Ashokan inscriptions",                 answer: "Maski",                     lat: 15.9,  lng: 76.7  },
  { year: 2017, number: 9,  hint: "An ancient port and trade centre",               answer: "Bhrigukachchha/Bharuch",    lat: 21.7,  lng: 73.0  },
  { year: 2017, number: 10, hint: "A Harappan site",                                answer: "Padri",                     lat: 21.2,  lng: 71.5  },
  { year: 2017, number: 11, hint: "A Chalcolithic site",                            answer: "Pandu Rajar Dhibi",         lat: 23.3,  lng: 87.9  },
  { year: 2017, number: 12, hint: "An ancient capital city",                        answer: "Rajgir/Rajagriha",          lat: 25.0,  lng: 85.4  },
  { year: 2017, number: 13, hint: "A Rock-cut cave site",                           answer: "Ellora",                    lat: 20.0,  lng: 75.2  },
  { year: 2017, number: 14, hint: "An early fortified city",                        answer: "Sisupalgarh",               lat: 20.2,  lng: 85.9  },
  { year: 2017, number: 15, hint: "A Rock-cut temple site",                         answer: "Masroor",                   lat: 32.1,  lng: 76.4  },
  { year: 2017, number: 16, hint: "An ancient temple site",                         answer: "Deogarh",                   lat: 24.5,  lng: 78.2  },
  { year: 2017, number: 17, hint: "An ancient capital city",                        answer: "Nagarjunakonda/Vijayapuri", lat: 16.5,  lng: 79.3  },
  { year: 2017, number: 18, hint: "An ancient temple site",                         answer: "Pushkar",                   lat: 26.5,  lng: 74.6  },
  { year: 2017, number: 19, hint: "A Palaeolithic site",                            answer: "Attirampakkam",             lat: 13.2,  lng: 79.9  },
  { year: 2017, number: 20, hint: "An ancient capital city",                        answer: "Pragjyotishpura",           lat: 26.2,  lng: 91.7  },

  // ── 2018 ──────────────────────────────────────────────────────────────────
  { year: 2018, number: 1,  hint: "Megalithic burial site",                         answer: "Adichanallur",              lat: 8.7,   lng: 77.8  },
  { year: 2018, number: 2,  hint: "Chalcolithic site",                              answer: "Gilund",                    lat: 25.5,  lng: 74.1  },
  { year: 2018, number: 3,  hint: "Cave Paintings",                                 answer: "Ajanta",                    lat: 20.6,  lng: 75.7  },
  { year: 2018, number: 4,  hint: "Palaeolithic site",                              answer: "Attirampakkam",             lat: 13.2,  lng: 79.9  },
  { year: 2018, number: 5,  hint: "Political and cultural centre",                  answer: "Hampi",                     lat: 15.3,  lng: 76.5  },
  { year: 2018, number: 6,  hint: "Terracotta centre",                              answer: "Chandraketugarh",           lat: 22.7,  lng: 88.6  },
  { year: 2018, number: 7,  hint: "Harappan site",                                  answer: "Kuntasi",                   lat: 22.5,  lng: 70.2  },
  { year: 2018, number: 8,  hint: "Vaishnav cultural site",                         answer: "Udaigiri/Beesnagar",        lat: 23.5,  lng: 77.8  },
  { year: 2018, number: 9,  hint: "Painted Grey Ware site",                         answer: "Thapli",                    lat: 29.8,  lng: 78.6  },
  { year: 2018, number: 10, hint: "Chalcolithic site",                              answer: "Inamgaon",                  lat: 18.6,  lng: 74.5  },
  { year: 2018, number: 11, hint: "Early agricultural centre",                      answer: "Koldihwa",                  lat: 25.1,  lng: 81.7  },
  { year: 2018, number: 12, hint: "Early Harappan site",                            answer: "Kot Diji",                  lat: 27.3,  lng: 68.6  },
  { year: 2018, number: 13, hint: "An ancient temple",                              answer: "Shankaracharya temple",     lat: 34.1,  lng: 74.9  },
  { year: 2018, number: 14, hint: "Political and cultural centre",                  answer: "Hastinapur",                lat: 29.2,  lng: 78.0  },
  { year: 2018, number: 15, hint: "An ancient sea port",                            answer: "Muziris/Muchiris",          lat: 10.2,  lng: 76.2  },
  { year: 2018, number: 16, hint: "Buddhist centre",                                answer: "Kanaganahalli",             lat: 16.1,  lng: 76.6  },
  { year: 2018, number: 17, hint: "Inscriptional site",                             answer: "Shatabgarhi",               lat: 34.5,  lng: 72.4  },
  { year: 2018, number: 18, hint: "An ancient capital",                             answer: "Sirpur",                    lat: 21.6,  lng: 82.8  },
  { year: 2018, number: 19, hint: "A Jaina centre",                                 answer: "Udaigiri/Khandagiri",       lat: 20.3,  lng: 85.8  },
  { year: 2018, number: 20, hint: "An ancient capital",                             answer: "Vaishali",                  lat: 25.7,  lng: 85.1  },

  // ── 2019 ──────────────────────────────────────────────────────────────────
  { year: 2019, number: 1,  hint: "Brick temple site",                              answer: "Bhitargaon",                lat: 26.3,  lng: 79.6  },
  { year: 2019, number: 2,  hint: "Early Harappa site",                             answer: "Banawali",                  lat: 29.6,  lng: 75.4  },
  { year: 2019, number: 3,  hint: "Ancient seaport and trade centre",               answer: "Muziris/Muchiris",          lat: 10.2,  lng: 76.2  },
  { year: 2019, number: 4,  hint: "Stone Age site",                                 answer: "Chopani Mando",             lat: 25.4,  lng: 81.9  },
  { year: 2019, number: 5,  hint: "Neolithic site",                                 answer: "Burzahom",                  lat: 34.2,  lng: 74.9  },
  { year: 2019, number: 6,  hint: "Archaeological site",                            answer: "Ropar",                     lat: 30.9,  lng: 76.5  },
  { year: 2019, number: 7,  hint: "Ancient capital city",                           answer: "Kaushambi",                 lat: 25.4,  lng: 81.4  },
  { year: 2019, number: 8,  hint: "Ancient capital",                                answer: "Ujjayini",                  lat: 23.2,  lng: 75.8  },
  { year: 2019, number: 9,  hint: "Harappan site",                                  answer: "Lothal",                    lat: 22.5,  lng: 72.2  },
  { year: 2019, number: 10, hint: "Ancient inscriptional site",                     answer: "Junagarh",                  lat: 21.5,  lng: 70.5  },
  { year: 2019, number: 11, hint: "A Rock-cut cave site",                           answer: "Pandavleni caves",          lat: 19.9,  lng: 73.7  },
  { year: 2019, number: 12, hint: "Ancient capital city",                           answer: "Banavasi",                  lat: 14.5,  lng: 75.0  },
  { year: 2019, number: 13, hint: "Famous temple site",                             answer: "Thanjavur",                 lat: 10.8,  lng: 79.1  },
  { year: 2019, number: 14, hint: "Centre of School of art",                        answer: "Amaravati",                 lat: 16.6,  lng: 80.4  },
  { year: 2019, number: 15, hint: "Ancient inscriptional site",                     answer: "Hathigumpha inscription",   lat: 20.3,  lng: 85.8  },
  { year: 2019, number: 16, hint: "Ancient education centre",                       answer: "Nalanda",                   lat: 25.1,  lng: 85.4  },
  { year: 2019, number: 17, hint: "Pre-Harappan site",                              answer: "Mehrgarh",                  lat: 29.4,  lng: 67.6  },
  { year: 2019, number: 18, hint: "Chalcolithic-period site",                       answer: "Inamgaon",                  lat: 18.6,  lng: 74.5  },
  { year: 2019, number: 19, hint: "Early inscriptional site",                       answer: "Mahasthangarh",             lat: 24.9,  lng: 89.4  },
  { year: 2019, number: 20, hint: "Ancient Petroglyphs site",                       answer: "Kandanali",                 lat: 11.2,  lng: 76.9  },

  // ── 2020 ──────────────────────────────────────────────────────────────────
  { year: 2020, number: 1,  hint: "Palaeolithic site",                              answer: "Paisra",                    lat: 24.9,  lng: 85.6  },
  { year: 2020, number: 2,  hint: "Palaeolithic factory site",                      answer: "Hunsgi",                    lat: 16.8,  lng: 76.6  },
  { year: 2020, number: 3,  hint: "Neolithic site",                                 answer: "Koldihwa",                  lat: 25.1,  lng: 81.7  },
  { year: 2020, number: 4,  hint: "Early and mature Harappan site",                 answer: "Padri",                     lat: 21.2,  lng: 71.5  },
  { year: 2020, number: 5,  hint: "Chalcolithic site",                              answer: "Navdatoli",                 lat: 22.3,  lng: 75.7  },
  { year: 2020, number: 6,  hint: "Site of Coin and Seal Moulds",                   answer: "Sunet",                     lat: 30.8,  lng: 75.9  },
  { year: 2020, number: 7,  hint: "Ancient Administration centre",                  answer: "Sylhet district",           lat: 24.9,  lng: 91.9  },
  { year: 2020, number: 8,  hint: "Ancient Political Headquarter",                  answer: "Karur",                     lat: 10.9,  lng: 78.1  },
  { year: 2020, number: 9,  hint: "Ancient Temple site",                            answer: "Srinagar (Shankaracharya)", lat: 34.1,  lng: 74.9  },
  { year: 2020, number: 10, hint: "Pre and Proto Historic site",                    answer: "Ganeshwar",                 lat: 27.7,  lng: 75.8  },
  { year: 2020, number: 11, hint: "Ancient capital city",                           answer: "Sisupalgarh",               lat: 20.2,  lng: 85.9  },
  { year: 2020, number: 12, hint: "Place of Shaiva Temple",                         answer: "Ramappa Temple",            lat: 17.9,  lng: 79.9  },
  { year: 2020, number: 13, hint: "World Heritage Centre of Temple complex",        answer: "Pattadakal",                lat: 15.9,  lng: 75.8  },
  { year: 2020, number: 14, hint: "An inscriptional site",                          answer: "Bicholim",                  lat: 15.6,  lng: 74.0  },
  { year: 2020, number: 15, hint: "Place of Jain Temple",                           answer: "Ellora",                    lat: 20.0,  lng: 75.2  },
  { year: 2020, number: 16, hint: "Largest Buddhist Monastery",                     answer: "Tawang Monastery",          lat: 27.6,  lng: 91.9  },
  { year: 2020, number: 17, hint: "Ancient Temple Complex",                         answer: "Masroor",                   lat: 32.1,  lng: 76.4  },
  { year: 2020, number: 18, hint: "Place of oldest Mosque",                         answer: "Cheraman Juma Mosque",      lat: 10.9,  lng: 75.9  },
  { year: 2020, number: 19, hint: "Temple complex dedicated to Shiva",              answer: "Bhoramdev Temple",          lat: 20.4,  lng: 81.3  },
  { year: 2020, number: 20, hint: "Ancient Education Centre",                       answer: "Nalanda",                   lat: 25.1,  lng: 85.4  },

  // ── 2021 ──────────────────────────────────────────────────────────────────
  { year: 2021, number: 1,  hint: "Palaeolithic site",                              answer: "Attirampakkam",             lat: 13.2,  lng: 79.9  },
  { year: 2021, number: 2,  hint: "Mesolithic site",                                answer: "Langhanaj",                 lat: 23.5,  lng: 72.4  },
  { year: 2021, number: 3,  hint: "Neolithic site",                                 answer: "Daojali Hading",            lat: 25.1,  lng: 93.4  },
  { year: 2021, number: 4,  hint: "Neolithic-Chalcolithic site",                    answer: "Mehrgarh",                  lat: 29.4,  lng: 67.6  },
  { year: 2021, number: 5,  hint: "Harappan site",                                  answer: "Manda",                     lat: 32.5,  lng: 75.1  },
  { year: 2021, number: 6,  hint: "Proto-historic and historic site",               answer: "Ropar",                     lat: 30.9,  lng: 76.5  },
  { year: 2021, number: 7,  hint: "Inscriptional site",                             answer: "Sohgaura",                  lat: 26.8,  lng: 83.8  },
  { year: 2021, number: 8,  hint: "Jain monastic site",                             answer: "Udayagiri-Khandagiri",      lat: 20.3,  lng: 85.8  },
  { year: 2021, number: 9,  hint: "Coin hoard",                                     answer: "Bayana",                    lat: 26.9,  lng: 77.3  },
  { year: 2021, number: 10, hint: "Palaeolithic site",                              answer: "Hunsgi",                    lat: 16.8,  lng: 76.6  },
  { year: 2021, number: 11, hint: "Terracotta site",                                answer: "Chandraketugarh",           lat: 22.7,  lng: 88.6  },
  { year: 2021, number: 12, hint: "Rock-cut caves",                                 answer: "Udaigiri",                  lat: 23.5,  lng: 77.8  },
  { year: 2021, number: 13, hint: "Ancient learning centre",                        answer: "Vallabhi",                  lat: 21.9,  lng: 71.9  },
  { year: 2021, number: 14, hint: "Political and Cultural centre",                  answer: "Sirpur",                    lat: 21.6,  lng: 82.8  },
  { year: 2021, number: 15, hint: "Buddhist site",                                  answer: "Sankissa",                  lat: 27.7,  lng: 79.8  },
  { year: 2021, number: 16, hint: "Ancient port",                                   answer: "Bhrigukachchha/Bharuch",    lat: 21.7,  lng: 73.0  },
  { year: 2021, number: 17, hint: "Early historic site",                            answer: "Sivakalai",                 lat: 8.6,   lng: 77.9  },
  { year: 2021, number: 18, hint: "Ivory hoard",                                    answer: "Bagram",                    lat: 34.9,  lng: 69.0  },
  { year: 2021, number: 19, hint: "Buddhist monastic centre",                       answer: "Somapura",                  lat: 25.0,  lng: 88.9  },
  { year: 2021, number: 20, hint: "Temple complex",                                 answer: "Kedarnath",                 lat: 30.7,  lng: 79.1  },

  // ── 2022 ──────────────────────────────────────────────────────────────────
  { year: 2022, number: 1,  hint: "Palaeolithic site",                              answer: "Didwana",                   lat: 27.4,  lng: 74.6  },
  { year: 2022, number: 2,  hint: "Mesolithic site with burials",                   answer: "Sarai Nahar Rai",           lat: 25.4,  lng: 81.9  },
  { year: 2022, number: 3,  hint: "Neolithic pit dwelling",                         answer: "Burzahom",                  lat: 34.2,  lng: 74.9  },
  { year: 2022, number: 4,  hint: "Early village settlement",                       answer: "Mehrgarh",                  lat: 29.4,  lng: 67.6  },
  { year: 2022, number: 5,  hint: "Neolithic site",                                 answer: "Edakkal caves",             lat: 11.6,  lng: 76.1  },
  { year: 2022, number: 6,  hint: "Neolithic-Chalcolithic site",                    answer: "Chirand",                   lat: 25.9,  lng: 84.7  },
  { year: 2022, number: 7,  hint: "Harappan UNESCO site",                           answer: "Dholavira",                 lat: 23.9,  lng: 70.2  },
  { year: 2022, number: 8,  hint: "Megalithic burial site",                         answer: "Maski",                     lat: 15.9,  lng: 76.7  },
  { year: 2022, number: 9,  hint: "Place of second Sangam",                         answer: "Kapatapuram",               lat: 9.9,   lng: 78.4  },
  { year: 2022, number: 10, hint: "Earliest Satavahana capital",                    answer: "Dhanyakataka/Amaravati",    lat: 16.6,  lng: 80.4  },
  { year: 2022, number: 11, hint: "Place of inscribed statue of Ashoka",            answer: "Kanaganahalli",             lat: 16.1,  lng: 76.6  },
  { year: 2022, number: 12, hint: "First Gupta hoard of coins",                     answer: "Kalighat",                  lat: 22.5,  lng: 88.3  },
  { year: 2022, number: 13, hint: "Hoard of metal sculptures",                      answer: "Kurkihar",                  lat: 24.8,  lng: 85.0  },
  { year: 2022, number: 14, hint: "Ancient port",                                   answer: "Bhrigukachchha",            lat: 21.7,  lng: 73.0  },
  { year: 2022, number: 15, hint: "Oldest Jesuit church",                           answer: "Basilica of Bom Jesus",     lat: 15.5,  lng: 73.9  },
  { year: 2022, number: 16, hint: "Centre of Gandhara art",                         answer: "Bamyan",                    lat: 34.8,  lng: 67.8  },
  { year: 2022, number: 17, hint: "Buddhist Monastery",                             answer: "Somapura",                  lat: 25.0,  lng: 88.9  },
  { year: 2022, number: 18, hint: "Place of earliest Vishnu Temple",                answer: "Dashavatara temple, Deogarh", lat: 24.5, lng: 78.2 },
  { year: 2022, number: 19, hint: "Shiva and Buddhist temple complex",              answer: "Sirpur",                    lat: 21.6,  lng: 82.8  },
  { year: 2022, number: 20, hint: "Earliest Chaitya Griha",                         answer: "Bhaja Cave",                lat: 18.7,  lng: 73.5  },

  // ── 2023 ──────────────────────────────────────────────────────────────────
  { year: 2023, number: 1,  hint: "Neolithic site",                                 answer: "Burzahom",                  lat: 34.2,  lng: 74.9  },
  { year: 2023, number: 2,  hint: "Site of mother and child terracotta figure",     answer: "Kannauj",                   lat: 27.1,  lng: 79.9  },
  { year: 2023, number: 3,  hint: "Hoard of Gupta coin",                            answer: "Bayana",                    lat: 26.9,  lng: 77.3  },
  { year: 2023, number: 4,  hint: "Site of botanical remains",                      answer: "Lahuradeva",                lat: 26.9,  lng: 83.5  },
  { year: 2023, number: 5,  hint: "Harappan site with mud-brick platform",          answer: "Ahar",                      lat: 24.6,  lng: 73.7  },
  { year: 2023, number: 6,  hint: "Mauryan reservoir site",                         answer: "Sudarshan Lake, Junagarh",  lat: 21.5,  lng: 70.5  },
  { year: 2023, number: 7,  hint: "Capital of Maitraka dynasty",                    answer: "Vallabhi",                  lat: 21.9,  lng: 71.9  },
  { year: 2023, number: 8,  hint: "Dockyard",                                       answer: "Lothal",                    lat: 22.5,  lng: 72.2  },
  { year: 2023, number: 9,  hint: "Rock shelter",                                   answer: "Bhimbetka",                 lat: 22.9,  lng: 77.6  },
  { year: 2023, number: 10, hint: "Stone axe factory",                              answer: "Nevasa",                    lat: 19.6,  lng: 74.7  },
  { year: 2023, number: 11, hint: "Satavahana inscription site",                    answer: "Nashik",                    lat: 19.9,  lng: 73.8  },
  { year: 2023, number: 12, hint: "Minor rock inscription of Ashoka",               answer: "Erragudi",                  lat: 14.9,  lng: 78.3  },
  { year: 2023, number: 13, hint: "Buddhist Stupa",                                 answer: "Phanigiri",                 lat: 17.1,  lng: 79.4  },
  { year: 2023, number: 14, hint: "Mesolithic site",                                answer: "Renigunta",                 lat: 13.6,  lng: 79.5  },
  { year: 2023, number: 15, hint: "Iron smelting workshop",                         answer: "Junapani",                  lat: 21.3,  lng: 79.1  },
  { year: 2023, number: 16, hint: "Megalithic site",                                answer: "Paiyampalli",               lat: 12.4,  lng: 78.7  },
  { year: 2023, number: 17, hint: "Temple dedicated to Surya",                      answer: "Mandsaur",                  lat: 24.1,  lng: 75.1  },
  { year: 2023, number: 18, hint: "Roman factory site",                             answer: "Arikamedu",                 lat: 11.9,  lng: 79.8  },
  { year: 2023, number: 19, hint: "Site of Muvar Koil",                             answer: "Kodumbalur",                lat: 11.1,  lng: 78.8  },
  { year: 2023, number: 20, hint: "Megalith stone site",                            answer: "Maski",                     lat: 15.9,  lng: 76.7  },

  // ── 2024 ──────────────────────────────────────────────────────────────────
  { year: 2024, number: 1,  hint: "Prehistoric site",                               answer: "Asurgarh",                  lat: 20.2,  lng: 83.4  },
  { year: 2024, number: 2,  hint: "Area of Petroglyphs",                            answer: "Konkan Coast",              lat: 16.5,  lng: 73.3  },
  { year: 2024, number: 3,  hint: "Neolithic site",                                 answer: "Barudih",                   lat: 22.8,  lng: 85.9  },
  { year: 2024, number: 4,  hint: "Harappan site",                                  answer: "Rakhigarhi",                lat: 29.3,  lng: 76.1  },
  { year: 2024, number: 5,  hint: "Buddhist monastery",                             answer: "Moghalmari Monastery",      lat: 22.2,  lng: 87.5  },
  { year: 2024, number: 6,  hint: "Chalcolithic site",                              answer: "Navdatoli",                 lat: 22.3,  lng: 75.7  },
  { year: 2024, number: 7,  hint: "Neo-Chalcolithic",                               answer: "Jodhpura",                  lat: 27.4,  lng: 75.6  },
  { year: 2024, number: 8,  hint: "Megalithic site with rock art",                  answer: "Mallapadi",                 lat: 11.5,  lng: 77.5  },
  { year: 2024, number: 9,  hint: "Mahajanapada of Buddha's miracles",             answer: "Shravasti",                 lat: 27.5,  lng: 82.1  },
  { year: 2024, number: 10, hint: "Hominid fossil find site",                       answer: "Hathnora",                  lat: 23.1,  lng: 77.5  },
  { year: 2024, number: 11, hint: "Major rock edict of Ashoka",                     answer: "Kalsi",                     lat: 30.5,  lng: 77.8  },
  { year: 2024, number: 12, hint: "Ancient trade centre",                           answer: "Dantapuram",                lat: 18.8,  lng: 84.1  },
  { year: 2024, number: 13, hint: "Stone inscription recording land grants",        answer: "Nashik",                    lat: 19.9,  lng: 73.8  },
  { year: 2024, number: 14, hint: "Shiva temples named after family relationships", answer: "Mama Bhanja temple, Sirpur", lat: 21.6, lng: 82.8  },
  { year: 2024, number: 15, hint: "Place of art related inscription",               answer: "Sittanavasal",              lat: 10.5,  lng: 78.9  },
  { year: 2024, number: 16, hint: "Place of inscription of three languages",        answer: "Maski",                     lat: 15.9,  lng: 76.7  },
  { year: 2024, number: 17, hint: "Temple site where three styles of architecture", answer: "Pattadakal",                lat: 15.9,  lng: 75.8  },
  { year: 2024, number: 18, hint: "Jain pilgrimage site",                           answer: "Vallabhi",                  lat: 21.9,  lng: 71.9  },
  { year: 2024, number: 19, hint: "Shiva temple of Gupta period",                   answer: "Dah Parbatiya",             lat: 26.5,  lng: 92.7  },
  { year: 2024, number: 20, hint: "Megalithic monumental site",                     answer: "Vangchhia",                 lat: 23.5,  lng: 92.7  },

  // ── 2025 ──────────────────────────────────────────────────────────────────
  { year: 2025, number: 1,  hint: "Neolithic site",                                 answer: "Giak and Kiari",            lat: 34.3,  lng: 77.6  },
  { year: 2025, number: 2,  hint: "Mesolithic site",                                answer: "Chandravadi",               lat: 22.1,  lng: 72.6  },
  { year: 2025, number: 3,  hint: "Palaeolithic site",                              answer: "Hallur",                    lat: 14.5,  lng: 75.9  },
  { year: 2025, number: 4,  hint: "Neolithic site with stone artefacts",            answer: "Koldihwa",                  lat: 25.1,  lng: 81.7  },
  { year: 2025, number: 5,  hint: "Site of Indus Valley Civilisation",              answer: "Rojdi",                     lat: 22.0,  lng: 70.8  },
  { year: 2025, number: 6,  hint: "Early Harappan site with a fire-pit",            answer: "Kalibangan",                lat: 29.5,  lng: 74.1  },
  { year: 2025, number: 7,  hint: "Late Harappan site",                             answer: "Alamgirpur/Sinauli",        lat: 28.9,  lng: 77.7  },
  { year: 2025, number: 8,  hint: "The Ochre Coloured Pottery (OCP) site",          answer: "Lal Qila",                  lat: 28.7,  lng: 77.2  },
  { year: 2025, number: 9,  hint: "Mesolithic site",                                answer: "Theemala",                  lat: 8.9,   lng: 76.8  },
  { year: 2025, number: 10, hint: "Megalithic site",                                answer: "Junapani",                  lat: 21.3,  lng: 79.1  },
  { year: 2025, number: 11, hint: "Mahajanapada of South India",                    answer: "Asmaka",                    lat: 18.8,  lng: 77.3  },
  { year: 2025, number: 12, hint: "Site of Buddha's Mahaparinirvana",               answer: "Kushinagar",                lat: 26.7,  lng: 83.9  },
  { year: 2025, number: 13, hint: "Major Rock Edict of Ashoka",                     answer: "Erragudi",                  lat: 14.9,  lng: 78.3  },
  { year: 2025, number: 14, hint: "Ashokan Minor Rock Edict",                       answer: "Sasaram",                   lat: 24.9,  lng: 84.0  },
  { year: 2025, number: 15, hint: "Commercial centre of Mauryas",                   answer: "Tamralipti",                lat: 22.4,  lng: 87.9  },
  { year: 2025, number: 16, hint: "Saka-Kushan Coin Hoard",                         answer: "Ujjain",                    lat: 23.2,  lng: 75.8  },
  { year: 2025, number: 17, hint: "Inscription mentioning Ashvamedha sacrifice",    answer: "Ayodhya",                   lat: 26.8,  lng: 82.2  },
  { year: 2025, number: 18, hint: "Site of post-Mauryan burnt brick house",         answer: "Sisupalgarh",               lat: 20.2,  lng: 85.9  },
  { year: 2025, number: 19, hint: "Terracotta craft centre of post-Mauryan period", answer: "Chandraketugarh",           lat: 22.7,  lng: 88.6  },
  { year: 2025, number: 20, hint: "Important port of the Pallava period",           answer: "Kaveripuram",               lat: 11.1,  lng: 79.8  },
];

export const mapYears = [...new Set(mapData.map(e => e.year))].sort();
