export type Note = {
  slug: string;
  title: string;
  paper: 1 | 2;
  section: string;
  topic: number;
  subtopics?: string[];
  description: string;
};

export const paper1Notes: Note[] = [
  { slug: 'sources-ancient-india', title: 'Sources of Ancient Indian History', paper: 1, section: 'Ancient India', topic: 1, description: 'Archaeological, literary and foreign sources', subtopics: ['Archaeological Sources', 'Literary Sources', 'Foreign Accounts'] },
  { slug: 'prehistory-protohistory', title: 'Pre-history and Proto-history', paper: 1, section: 'Ancient India', topic: 2, description: 'Geographical factors, Palaeolithic, Mesolithic, Neolithic & Chalcolithic', subtopics: ['Palaeolithic Age', 'Mesolithic Age', 'Neolithic Age', 'Chalcolithic Age'] },
  { slug: 'indus-valley-civilization', title: 'Indus Valley Civilization', paper: 1, section: 'Ancient India', topic: 3, description: 'Origin, date, extent, characteristics, decline and significance', subtopics: ['Origin & Dating', 'Extent & Sites', 'Town Planning', 'Economy & Trade', 'Religion & Culture', 'Decline'] },
  { slug: 'megalithic-cultures', title: 'Megalithic Cultures', paper: 1, section: 'Ancient India', topic: 4, description: 'Pastoral and farming cultures outside Indus, iron industry, pottery', subtopics: ['Distribution', 'Community Life', 'Iron Industry', 'Pottery'] },
  { slug: 'aryans-vedic-period', title: 'Aryans and Vedic Period', paper: 1, section: 'Ancient India', topic: 5, description: 'Expansion of Aryans, Rig Vedic and Later Vedic society', subtopics: ['Aryan Expansion', 'Rig Vedic Period', 'Later Vedic Period', 'Social & Economic Life', 'Varna System'] },
  { slug: 'mahajanapadas', title: 'Period of Mahajanapadas', paper: 1, section: 'Ancient India', topic: 6, description: 'Formation of states, rise of Magadha, Buddhism & Jainism, coinage', subtopics: ['16 Mahajanapadas', 'Rise of Magadha', 'Buddhism', 'Jainism', 'Coinage'] },
  { slug: 'mauryan-empire', title: 'Mauryan Empire', paper: 1, section: 'Ancient India', topic: 7, description: 'Chandragupta, Kautilya, Ashoka, Dharma, administration, art', subtopics: ['Foundation', 'Chandragupta Maurya', 'Kautilya & Arthashastra', 'Ashoka', 'Concept of Dharma', 'Administration', 'Art & Architecture', 'Decline'] },
  { slug: 'post-mauryan-period', title: 'Post-Mauryan Period', paper: 1, section: 'Ancient India', topic: 8, description: 'Indo-Greeks, Sakas, Kushanas, Mahayana, art & culture', subtopics: ['Indo-Greeks', 'Sakas', 'Kushanas', 'Mahayana Buddhism', 'Gandhara Art'] },
  { slug: 'eastern-india-deccan-south', title: 'Early State & Society — East, Deccan & South', paper: 1, section: 'Ancient India', topic: 9, description: 'Kharavela, Satavahanas, Sangam Age Tamil States', subtopics: ['Kharavela', 'Satavahanas', 'Sangam Age', 'Tamil Literature & Culture'] },
  { slug: 'guptas-vakatakas-vardhanas', title: 'Guptas, Vakatakas and Vardhanas', paper: 1, section: 'Ancient India', topic: 10, description: 'Golden age, coinage, feudalism, Nalanda, literature & art', subtopics: ['Gupta Administration', 'Economy & Coinage', 'Indian Feudalism', 'Nalanda & Vikramshila', 'Literature & Science', 'Art & Architecture'] },
  { slug: 'regional-states-gupta-era', title: 'Regional States during Gupta Era', paper: 1, section: 'Ancient India', topic: 11, description: 'Pallavas, Chalukyas, Cholas, Palas, Rashtrakutas, temple architecture', subtopics: ['Kadambas & Pallavas', 'Chalukyas of Badami', 'Palas & Senas', 'Rashtrakutas', 'Cholas', 'Temple Architecture'] },
  { slug: 'early-indian-cultural-history', title: 'Themes in Early Indian Cultural History', paper: 1, section: 'Ancient India', topic: 12, description: 'Languages, art evolution, philosophy, science & mathematics', subtopics: ['Languages & Texts', 'Art & Architecture', 'Philosophy', 'Science & Mathematics'] },
  { slug: 'early-medieval-india', title: 'Early Medieval India (750–1200)', paper: 1, section: 'Medieval India', topic: 13, description: 'Rajputs, Cholas, agrarian economy, Indian feudalism', subtopics: ['Rajputs — Origin & Rise', 'Chola Administration', 'Village Economy', 'Trade & Commerce', 'Women\'s Condition'] },
  { slug: 'cultural-traditions-750-1200', title: 'Cultural Traditions in India (750–1200)', paper: 1, section: 'Medieval India', topic: 14, description: 'Shankaracharya, Bhakti, Sufism, Sanskrit & Tamil literature', subtopics: ['Vedanta & Advaita', 'Bhakti Movement', 'Islam & Sufism', 'Literature', 'Temple Architecture'] },
  { slug: 'thirteenth-century', title: 'The Thirteenth Century', paper: 1, section: 'Medieval India', topic: 15, description: 'Ghurian invasions, Delhi Sultanate, Iltutmish, Balban', subtopics: ['Ghurian Invasions', 'Foundation of Delhi Sultanate', 'Iltutmish', 'Balban'] },
  { slug: 'fourteenth-century', title: 'The Fourteenth Century', paper: 1, section: 'Medieval India', topic: 16, description: 'Khalji Revolution, Alauddin, Muhammad Tughluq, Firuz Tughluq', subtopics: ['Khalji Revolution', 'Alauddin Khalji', 'Muhammad Tughluq', 'Firuz Tughluq', 'Ibn Battuta'] },
  { slug: 'society-culture-economy-13-14c', title: 'Society, Culture & Economy — 13th & 14th Centuries', paper: 1, section: 'Medieval India', topic: 17, description: 'Rural society, Bhakti & Sufi movements, Persian literature, composite culture', subtopics: ['Rural Society', 'Bhakti Movement', 'Sufi Movement', 'Persian Literature', 'Sultanate Architecture'] },
  { slug: 'fifteenth-sixteenth-century-political', title: '15th & Early 16th Century — Political & Economic', paper: 1, section: 'Medieval India', topic: 18, description: 'Provincial dynasties, Vijayanagara, Lodis, Mughals, Sur Empire', subtopics: ['Provincial Dynasties', 'Vijayanagara Empire', 'Lodis', 'Babur & Humayun', 'Sher Shah Suri', 'Portuguese'] },
  { slug: 'fifteenth-sixteenth-century-society', title: '15th & Early 16th Century — Society & Culture', paper: 1, section: 'Medieval India', topic: 19, description: 'Regional cultures, literary traditions, Vijayanagara arts', subtopics: ['Regional Cultures', 'Literary Traditions', 'Provincial Architecture', 'Vijayanagara Arts'] },
  { slug: 'akbar', title: 'Akbar', paper: 1, section: 'Medieval India', topic: 20, description: 'Conquests, Mansabdari system, Rajput policy, Sulh-i-kul, Din-i-Ilahi', subtopics: ['Conquests & Consolidation', 'Mansabdari & Jagir', 'Rajput Policy', 'Religious Policy & Sulh-i-kul', 'Court Culture & Arts'] },
  { slug: 'mughal-empire-17th-century', title: 'Mughal Empire in the 17th Century', paper: 1, section: 'Medieval India', topic: 21, description: 'Jahangir, Shahjahan, Aurangzeb, Zamindars, Marathas, Ahom', subtopics: ['Jahangir & Shahjahan', 'Aurangzeb', 'Mughal State & Zamindars', 'Crisis & Revolts', 'Shivaji & Marathas', 'Ahom Kingdom'] },
  { slug: 'economy-society-16-17c', title: 'Economy & Society — 16th & 17th Centuries', paper: 1, section: 'Medieval India', topic: 22, description: 'Agriculture, towns, European trade, Sikh community', subtopics: ['Agricultural Production', 'Towns & Trade', 'European Companies', 'Peasants & Women', 'Sikh Community'] },
  { slug: 'mughal-culture', title: 'Culture during Mughal Empire', paper: 1, section: 'Medieval India', topic: 23, description: 'Persian histories, Mughal architecture, painting, music, science', subtopics: ['Persian & Hindi Literature', 'Mughal Architecture', 'Mughal Painting', 'Classical Music', 'Science & Technology'] },
  { slug: 'eighteenth-century', title: 'The Eighteenth Century', paper: 1, section: 'Medieval India', topic: 24, description: 'Mughal decline, regional powers, Maratha ascendancy, Battle of Panipat 1761', subtopics: ['Mughal Decline — Factors', 'Regional Principalities', 'Maratha Ascendancy', 'Afghan Power', 'Battle of Panipat 1761'] },
];

export const paper2Notes: Note[] = [
  { slug: 'european-penetration-india', title: 'European Penetration into India', paper: 2, section: 'Modern India', topic: 1, description: 'Portuguese, Dutch, English, French; Carnatic Wars; Battle of Plassey', subtopics: ['Early European Settlements', 'Portuguese & Dutch', 'English & French Companies', 'Carnatic Wars', 'Battle of Plassey'] },
  { slug: 'british-expansion-india', title: 'British Expansion in India', paper: 2, section: 'Modern India', topic: 2, description: 'Battle of Buxar, Mysore Wars, Anglo-Maratha Wars, Punjab', subtopics: ['Battle of Buxar', 'Mysore Wars', 'Anglo-Maratha Wars', 'Conquest of Punjab'] },
  { slug: 'early-british-raj', title: 'Early Structure of the British Raj', paper: 2, section: 'Modern India', topic: 3, description: 'Regulating Act, Pitt\'s India Act, Charter Act, Utilitarian thought', subtopics: ['Regulating Act 1773', 'Pitt\'s India Act 1784', 'Charter Act 1833', 'Utilitarians & India'] },
  { slug: 'economic-impact-british-rule', title: 'Economic Impact of British Colonial Rule', paper: 2, section: 'Modern India', topic: 4, description: 'Land revenue settlements, commercialization, de-industrialization, drain of wealth', subtopics: ['Permanent Settlement', 'Ryotwari Settlement', 'Mahalwari Settlement', 'Commercialisation of Agriculture', 'De-industrialisation', 'Drain of Wealth'] },
  { slug: 'social-cultural-developments', title: 'Social and Cultural Developments', paper: 2, section: 'Modern India', topic: 5, description: 'Education controversy, western education, press, vernacular literature', subtopics: ['Indigenous Education', 'Orientalist-Anglicist Controversy', 'Western Education', 'Press & Literature', 'Christian Missionaries'] },
  { slug: 'social-religious-reform', title: 'Social & Religious Reform Movements', paper: 2, section: 'Modern India', topic: 6, description: 'Ram Mohan Roy, Brahmo Movement, Dayananda, Wahabi, social reforms', subtopics: ['Ram Mohan Roy', 'Brahmo Movement', 'Iswarchandra Vidyasagar', 'Dayananda Saraswati', 'Wahabi & Feraizi Movements', 'Social Reforms'] },
  { slug: 'indian-response-british-rule', title: 'Indian Response to British Rule', paper: 2, section: 'Modern India', topic: 7, description: 'Tribal & peasant uprisings, Revolt of 1857', subtopics: ['Peasant & Tribal Uprisings', 'Revolt of 1857 — Causes', 'Character & Course', 'Causes of Failure', 'Consequences'] },
  { slug: 'birth-indian-nationalism', title: 'Birth of Indian Nationalism', paper: 2, section: 'Modern India', topic: 8, description: 'INC foundation, Moderates & Extremists, Swadeshi, Partition of Bengal', subtopics: ['Birth of Nationalism', 'Foundation of INC', 'Moderates', 'Extremists', 'Partition of Bengal', 'Swadeshi Movement'] },
  { slug: 'gandhian-nationalism', title: 'Rise of Gandhi & Gandhian Nationalism', paper: 2, section: 'Modern India', topic: 9, description: 'Rowlatt, Khilafat, Non-cooperation, Civil Disobedience, Quit India', subtopics: ['Rowlatt Satyagraha', 'Khilafat Movement', 'Non-cooperation Movement', 'Civil Disobedience', 'Round Table Conferences', 'Quit India Movement', 'Cabinet Mission'] },
  { slug: 'constitutional-developments', title: 'Constitutional Developments 1858–1935', paper: 2, section: 'Modern India', topic: 10, description: 'Acts and reforms from 1858 to Government of India Act 1935', subtopics: ['Act of 1858', 'Indian Councils Acts', 'Morley-Minto Reforms', 'Montagu-Chelmsford Reforms', 'Government of India Act 1935'] },
  { slug: 'other-strands-national-movement', title: 'Other Strands in the National Movement', paper: 2, section: 'Modern India', topic: 11, description: 'Revolutionary terrorism, Left & Congress Socialists, Communist Party', subtopics: ['Revolutionary Movement', 'Left within Congress', 'Nehru & Bose', 'Congress Socialist Party', 'Communist Party of India'] },
  { slug: 'politics-separatism-partition', title: 'Politics of Separatism & Partition', paper: 2, section: 'Modern India', topic: 12, description: 'Muslim League, Hindu Mahasabha, communalism, transfer of power', subtopics: ['Muslim League', 'Hindu Mahasabha', 'Communalism', 'Transfer of Power', 'Independence & Partition'] },
  { slug: 'post-independence-consolidation', title: 'Post-Independence Consolidation', paper: 2, section: 'Modern India', topic: 13, description: 'Nehru\'s foreign policy, linguistic reorganization, integration of princely states', subtopics: ['Nehru\'s Foreign Policy', 'India & Neighbours', 'Linguistic Reorganisation', 'Integration of Princely States'] },
  { slug: 'caste-ethnicity-post-1947', title: 'Caste and Ethnicity after 1947', paper: 2, section: 'Modern India', topic: 14, description: 'Backward castes, tribal politics, Dalit movements', subtopics: ['Backward Castes in Politics', 'Tribal Issues', 'Dalit Movements'] },
  { slug: 'economic-development-political-change', title: 'Economic Development & Political Change', paper: 2, section: 'Modern India', topic: 15, description: 'Land reforms, planning, ecology, science & technology post-independence', subtopics: ['Land Reforms', 'Planning & Rural Reconstruction', 'Environmental Policy', 'Progress of Science'] },
  { slug: 'enlightenment-modern-ideas', title: 'Enlightenment and Modern Ideas', paper: 2, section: 'World History', topic: 16, description: 'Kant, Rousseau, Enlightenment in colonies, Marxian Socialism', subtopics: ['Major Enlightenment Ideas', 'Kant & Rousseau', 'Enlightenment in Colonies', 'Rise of Socialism', 'Marxian Socialism'] },
  { slug: 'origins-modern-politics', title: 'Origins of Modern Politics', paper: 2, section: 'World History', topic: 17, description: 'American & French Revolutions, European states system, British democracy', subtopics: ['European States System', 'American Revolution', 'French Revolution', 'American Civil War', 'British Democratic Politics'] },
  { slug: 'industrialization', title: 'Industrialization', paper: 2, section: 'World History', topic: 18, description: 'English Industrial Revolution, USA, Germany, Russia, Japan', subtopics: ['English Industrial Revolution', 'Industrialisation in USA', 'Germany & Russia', 'Japan', 'Industrialisation & Globalisation'] },
  { slug: 'nation-state-system', title: 'Nation-State System', paper: 2, section: 'World History', topic: 19, description: '19th century nationalism, German & Italian unification, disintegration of empires', subtopics: ['Rise of Nationalism', 'German Unification', 'Italian Unification', 'Disintegration of Empires'] },
  { slug: 'imperialism-colonialism', title: 'Imperialism and Colonialism', paper: 2, section: 'World History', topic: 20, description: 'South-East Asia, Latin America, Africa, neo-imperialism', subtopics: ['South & South-East Asia', 'Latin America & South Africa', 'Australia', 'Neo-imperialism'] },
  { slug: 'revolution-counter-revolution', title: 'Revolution and Counter-Revolution', paper: 2, section: 'World History', topic: 21, description: '19th century revolutions, Russian Revolution, Fascism, Chinese Revolution', subtopics: ['19th Century Revolutions', 'Russian Revolution 1917', 'Fascism — Italy & Germany', 'Chinese Revolution 1949'] },
  { slug: 'world-wars', title: 'World Wars', paper: 2, section: 'World History', topic: 22, description: 'WWI & WWII causes, consequences and societal implications', subtopics: ['WWI — Causes', 'WWI — Consequences', 'WWII — Causes', 'WWII — Consequences', 'Wars as Total Wars'] },
  { slug: 'world-after-wwii', title: 'The World after World War II', paper: 2, section: 'World History', topic: 23, description: 'Two power blocs, Third World, Non-alignment, UNO', subtopics: ['Two Power Blocs', 'Third World & Non-alignment', 'UNO & Global Disputes'] },
  { slug: 'liberation-colonial-rule', title: 'Liberation from Colonial Rule', paper: 2, section: 'World History', topic: 24, description: 'Latin America, Arab World, Africa, Vietnam', subtopics: ['Latin America — Bolivar', 'Egypt', 'Africa — Apartheid to Democracy', 'Vietnam'] },
  { slug: 'decolonization-underdevelopment', title: 'Decolonization and Underdevelopment', paper: 2, section: 'World History', topic: 25, description: 'Factors constraining development — Latin America, Africa', subtopics: ['Development Constraints', 'Latin America', 'Africa'] },
  { slug: 'unification-europe', title: 'Unification of Europe', paper: 2, section: 'World History', topic: 26, description: 'NATO, European Community, consolidation and expansion, European Union', subtopics: ['Post-War Foundations', 'NATO', 'European Community', 'European Union'] },
  { slug: 'disintegration-soviet-union', title: 'Disintegration of Soviet Union & Unipolar World', paper: 2, section: 'World History', topic: 27, description: 'Collapse of Soviet communism, political changes in East Europe, US ascendancy', subtopics: ['Collapse of Soviet Communism', 'Political Changes in East Europe', 'End of Cold War', 'US as Sole Superpower'] },
];

export const allNotes = [...paper1Notes, ...paper2Notes];

export function getNoteBySlug(slug: string): Note | undefined {
  return allNotes.find(n => n.slug === slug);
}

export const paper1Sections = ['Ancient India', 'Medieval India'];
export const paper2Sections = ['Modern India', 'World History'];
