#!/usr/bin/env bash
#
# Regenerates supabase/schema.sql from the live database.
#
# The schema existed only in the Supabase dashboard. That cost us twice in one
# afternoon: a migration had to be guessed at because nobody knew that
# usage_tracking.fingerprint is NOT NULL, and two deploys went out against
# functions that had never been created. There was also no way to stand up a
# second environment.
#
# pg_dump is not used deliberately: Homebrew ships v14 while Supabase runs a
# newer server, and pg_dump refuses that pairing. psql introspection works
# against any version.
#
# Needs SUPABASE_DB_URL in .env.local — Supabase dashboard, Project Settings ->
# Database -> Connection string -> URI. Keep it there; .env.local is gitignored.
#
# Usage: ./scripts/dump-schema.sh

set -euo pipefail
cd "$(dirname "$0")/.."

if [ -z "${SUPABASE_DB_URL:-}" ] && [ -f .env.local ]; then
  # `|| true` matters: under `set -e` a grep that matches nothing would abort
  # the script here, before the helpful message below could print.
  SUPABASE_DB_URL="$(grep -E '^SUPABASE_DB_URL=' .env.local | head -1 | cut -d= -f2- | tr -d '"'"'"'' || true)"
fi

if [ -z "${SUPABASE_DB_URL:-}" ]; then
  echo "SUPABASE_DB_URL is not set. Add it to .env.local:" >&2
  echo "  SUPABASE_DB_URL=postgresql://postgres:PASSWORD@db.PROJECT.supabase.co:5432/postgres" >&2
  exit 1
fi

OUT=supabase/schema.sql
Q() { psql "$SUPABASE_DB_URL" -X -q -t -A --no-psqlrc -c "$1"; }

{
  echo "-- Generated by scripts/dump-schema.sh — do not edit by hand."
  echo "-- Regenerate after every schema change and commit the result."
  echo "-- Captures public-schema tables, constraints, indexes, functions,"
  echo "-- row-level security and triggers. Data is never included."
  echo "--"
  echo "-- Dumped: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo

  echo "-- ── Extensions ─────────────────────────────────────────────────────────"
  Q "select 'create extension if not exists ' || quote_ident(extname) || ';'
       from pg_extension where extname not in ('plpgsql') order by extname;"
  echo

  echo "-- ── Tables ─────────────────────────────────────────────────────────────"
  Q "select 'create table if not exists ' || quote_ident(c.relname) || ' (' || chr(10) ||
              string_agg(
                '  ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
                     || coalesce(' default ' || pg_get_expr(d.adbin, d.adrelid), '')
                     || case when a.attnotnull then ' not null' else '' end,
                ',' || chr(10) order by a.attnum)
           || chr(10) || ');' || chr(10)
       from pg_class c
       join pg_namespace n on n.oid = c.relnamespace
       join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
       left join pg_attrdef d on d.adrelid = c.oid and d.adnum = a.attnum
       where n.nspname = 'public' and c.relkind = 'r'
       group by c.relname order by c.relname;"
  echo

  echo "-- ── Constraints ────────────────────────────────────────────────────────"
  echo "-- Primary keys, uniques, foreign keys and checks. The unique columns"
  echo "-- here are what upsert onConflict targets rely on."
  Q "select 'alter table ' || quote_ident(rel.relname) ||
              ' add constraint ' || quote_ident(con.conname) || ' ' ||
              pg_get_constraintdef(con.oid) || ';'
       from pg_constraint con
       join pg_class rel on rel.oid = con.conrelid
       join pg_namespace n on n.oid = rel.relnamespace
       where n.nspname = 'public'
       order by rel.relname, con.contype desc, con.conname;"
  echo

  echo "-- ── Indexes ────────────────────────────────────────────────────────────"
  Q "select indexdef || ';' from pg_indexes
       where schemaname = 'public'
         and indexname not in (select conname from pg_constraint where contype in ('p','u'))
       order by tablename, indexname;"
  echo

  echo "-- ── Functions ──────────────────────────────────────────────────────────"
  echo "-- Extension-owned functions are excluded. pgvector alone installs ~95 of"
  echo "-- them into public (halfvec_*, vector_*), which would conflict on replay"
  echo "-- and bury the handful this project actually defines."
  Q "select pg_get_functiondef(p.oid) || ';' || chr(10)
       from pg_proc p
       join pg_namespace n on n.oid = p.pronamespace
       where n.nspname = 'public' and p.prokind = 'f'
         and not exists (
           select 1 from pg_depend d
            where d.objid = p.oid and d.deptype = 'e'
         )
       order by p.proname;"
  echo

  echo "-- ── Row-level security ─────────────────────────────────────────────────"
  Q "select 'alter table ' || quote_ident(c.relname) || ' enable row level security;'
       from pg_class c join pg_namespace n on n.oid = c.relnamespace
       where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity
       order by c.relname;"
  echo
  echo "-- Policies. A table with RLS on and no policy denies every non-service role."
  Q "select 'create policy ' || quote_ident(policyname) || ' on ' || quote_ident(tablename) ||
              ' as ' || permissive || ' for ' || cmd ||
              ' to ' || array_to_string(roles, ', ') ||
              coalesce(' using (' || qual || ')', '') ||
              coalesce(' with check (' || with_check || ')', '') || ';'
       from pg_policies where schemaname = 'public'
       order by tablename, policyname;"
  echo

  echo "-- ── Triggers ───────────────────────────────────────────────────────────"
  Q "select pg_get_triggerdef(t.oid) || ';'
       from pg_trigger t
       join pg_class c on c.oid = t.tgrelid
       join pg_namespace n on n.oid = c.relnamespace
       where n.nspname = 'public' and not t.tgisinternal
       order by c.relname, t.tgname;"
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
